# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 07:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160117_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cid',
        ),
        migrations.AddField(
            model_name='product',
            name='cid',
            field=models.ManyToManyField(to='app.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 17, 7, 12, 53, 795772, tzinfo=utc)),
        ),
    ]
