# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 07:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160117_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cid',
        ),
        migrations.AddField(
            model_name='product',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 17, 7, 22, 18, 848852, tzinfo=utc)),
        ),
    ]
