# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 04:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160104_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 4, 4, 56, 26, 82428, tzinfo=utc)),
        ),
    ]
