# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 03:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160120_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingadress',
            name='street',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='permanentaddress',
            name='street',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 20, 3, 23, 57, 289126, tzinfo=utc)),
        ),
    ]
