# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 03:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160120_0323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingAdress',
            new_name='BillingAddress',
        ),
        migrations.AlterField(
            model_name='product',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 20, 3, 37, 0, 27797, tzinfo=utc)),
        ),
    ]
