# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 05:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160110_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 10, 5, 46, 32, 877856, tzinfo=utc)),
        ),
    ]
