# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 12:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20160120_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='acct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserProf'),
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='acct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserProf'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 20, 12, 55, 14, 939290, tzinfo=utc)),
        ),
    ]
