# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 14:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160120_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 20, 14, 39, 33, 797593, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprof',
            name='fname',
            field=models.CharField(default='First Name', max_length=120),
        ),
        migrations.AlterField(
            model_name='userprof',
            name='lname',
            field=models.CharField(default='Last Name', max_length=120),
        ),
    ]
