# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 01:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20160121_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='brgy',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='pnum',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='postalcode',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='street',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='brgy',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='city',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='pnum',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='postalcode',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='state',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='street',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 21, 1, 45, 59, 193242, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprof',
            name='fname',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AlterField(
            model_name='userprof',
            name='lname',
            field=models.CharField(default=' ', max_length=120),
        ),
    ]
