# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 15:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20160123_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 23, 15, 9, 35, 257246, tzinfo=utc)),
        ),
    ]
