# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 15:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20160123_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 23, 15, 12, 10, 448043, tzinfo=utc)),
        ),
    ]
