# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 15:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20160123_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 23, 15, 12, 14, 457808, tzinfo=utc)),
        ),
    ]
