# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 15:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20160123_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img1',
            field=models.FileField(default='/media/pimages/noimage.jpg', upload_to='pimages'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img2',
            field=models.FileField(default='/media/pimages/noimage.jpg', upload_to='pimages'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img3',
            field=models.FileField(default='/media/pimages/noimage.jpg', upload_to='pimages'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img4',
            field=models.FileField(default='/media/pimages/noimage.jpg', upload_to='pimages'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img5',
            field=models.FileField(default='/media/pimages/noimage.jpg', upload_to='pimages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 23, 15, 37, 7, 30462, tzinfo=utc)),
        ),
    ]
