# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 02:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20160123_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 24, 2, 20, 29, 55272, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sname',
            field=models.CharField(default='None', max_length=120),
        ),
    ]
