# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 14:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20160128_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='purdate',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 28, 14, 59, 54, 537385, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 28, 14, 59, 54, 531249, tzinfo=utc)),
        ),
    ]
