# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 03:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20160128_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Shop'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='purdate',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 18, 3, 28, 29, 744751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 18, 3, 28, 29, 741706, tzinfo=utc)),
        ),
    ]
