# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 03:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20160218_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.FileField(default='pimages/noimage.jpg', upload_to='pimages'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='purdate',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 24, 3, 44, 15, 769657, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 24, 3, 44, 15, 766555, tzinfo=utc)),
        ),
    ]
