# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 03:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20160224_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='purdate',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 24, 3, 44, 30, 455876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 24, 3, 44, 30, 452761, tzinfo=utc)),
        ),
    ]
